### ISSUE TITLE
Waiting for remote file status forever

### ISSUE THREAD

**Issue by kvshams** [broadinstitute/single_cell_portal#103]
Hi,
I am creating a study with 300k cells and uploaded the count table as expression table. Visualisation is initiated and can see all the cells, but I am not able to get all the genes, most of them are ubiquitously expressed genes such as actins (seems to be those genes have more dense data). When I am looking at the data, the count table shows, waiting for remote files. This is persisting over a month. I have tried recreating another study, still the same issue. Will update this comment with the screenshot once the single cell portal is up.

**Comment by jlchang** [comment]
Hi @kvshams,

I'll be happy to investigate your issue, thank you for connecting with me through scp-support@broadinstitute.zendesk.com.

I'll retain this issue until we record a root cause of the problem in case it will be helpful for others who experience a similar issue.

**Comment by jlchang** [comment]
Hi @kvshams,

"Awaiting remote file" should be a transient state that shouldn't last for more than a few hours. If it persists for more than 24 hours, it is most likely that the file upload was interrupted (either due to low internet connectivity or possibly accidental navigation away from the Portal page during upload) causing your file to be stuck.

If you should see "Awaiting remote file" persist, please email [scp-support@broadinstitute.zendesk.com](scp-support@broadinstitute.zendesk.com) with your study accession or link to your study so we can clear the file of the stuck status.
