### ISSUE TITLE
Cannot add study on the https://portals.broadinstitute.org/single_cell

### ISSUE THREAD

**Issue by wulabupenn** [broadinstitute/single_cell_portal#19]
When I clicked "+ New Study" button, there was a warning showing "We're sorry, but something went wrong". I attached the figures for the problem. I am wondering how could I add a study on the website. Thank you!
![upload_problem1](https://user-images.githubusercontent.com/33881425/35482419-d7ccce38-0402-11e8-97c4-e85a09f9b8f9.png)
![upload_problem2](https://user-images.githubusercontent.com/33881425/35482420-d7d92034-0402-11e8-8b64-97f69e844d5e.png)

**Comment by bistline** [comment]
I see the problem now - this has to do with FireCloud access and the fact that you haven't registered with FireCloud yet.  This is definitely a bug (it shouldn't be required first), but there is a workaround until I can patch this.

Log in to the portal with your Google account, and then instead of trying to add a study, open the Profile menu (dropdown in the top righthand corner that shows your username) and click 'My Profile'.  Open the tab that says 'FireCloud Profile', fill out all the fields and click 'Update Profile'.  Once this is saved, you will be able to add new studies to the portal.

Let me know if you still have issues.
