### ISSUE TITLE
Files only downloadable by some accounts?

### ISSUE THREAD

**Issue by farrellja** [broadinstitute/single_cell_portal#23]
Hi Team,

This concerns study: "Single-cell Reconstruction of Developmental Trajectories During Zebrafish Embryogenesis"

It seems that I can download files from the study after logging in using my account from the website, but my labmates cannot after logging in with their accounts. They receive a 404 File Not Found error. However, one (enterprising) labmate WAS able to download the file using curl from the bulk download command even though the website did not work for her.

Not quite sure what is going on there! Can you help?

Thanks!!
Jeff

**Comment by eweitz** [comment]
Hi @farrellja, this was likely caused by a rare outage in Google Cloud Platform.  GCP services seem to be [back to normal](https://status.cloud.google.com/).  Could you please try again?

**Comment by farrellja** [comment]
Hi @eweitz! Unfortunately, it doesn't seem to have corrected the problem for my labmate. She just got the 404 error from the website again after logging out and then logging back in.

**Comment by bistline** [comment]
Jeff -

Can you try again?  I refreshed all of our API client connections and it appears to be working again.  I'm not sure what the root cause is, but I believe it had something to do with the outage on Google & FireCloud yesterday, and the cached storage drivers we use in production.

Let me know if you still can't access any data.
