### ISSUE TITLE
what is wrong with this file?

### ISSUE THREAD

**Issue by allonw** [broadinstitute/single_cell_portal#6]
I've been trying to upload a coords file, but this file is not parsed even though it seems to satisfy the requirements.

I'm attaching also the cluster labels file, which didn't parse until I changed the tab delimiters to comma (this workaround doesn't work for the coords file)

thanks
[cluster_coords.txt](https://github.com/broadinstitute/single_cell_portal/files/613925/cluster_coords.txt)
[cluster_labels_comma.txt](https://github.com/broadinstitute/single_cell_portal/files/613924/cluster_labels_comma.txt)

**Comment by bistline** [comment]
Allon -

This appears to be a line-endings issue, which is odd because it shouldn't matter.  The short-term workaround in to make sure that the files have Unix (LF) line endings.  Windows (CRLF) will also work.  When I downloaded this file to test, it somehow had legacy MacOS line endings (CR) that the portal didn't know how to parse.

I'm going to add more logic to catch this in the future, but I was able to get your file to work by changing the line endings.
