### ISSUE TITLE
What is daily quota?

### ISSUE THREAD

**Issue by zhanxw** [broadinstitute/single_cell_portal#63]
Hi, 

I downloaded <10 files and had this warning:

    Forbidden: You have exceeded your current daily download quota.  You must wait until tomorrow to download this object.

What is the daily quota? How to bypass it (need to download >50 files)?
Any other way to download in addition to curl?

Here is my error message:

```
> curl "https://portals.broadinstitute.org/single_cell/bulk_data/SCP354/slide-seq-study/all/539855" -o cfg.txt
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   118    0   118    0     0    280      0 --:--:-- --:--:-- --:--:--   290
> cat cfg.txt
Forbidden: You have exceeded your current daily download quota.  You must wait until tomorrow to download this object.

```

**Comment by vickylihorst** [comment]
Hi @zhanxw, we set a daily download quota (currently 0.5 terabyte) to protect us from large downloads that cause us to exceed our budget, as every download incurs an egress fee that we (SCP) pay to Google Cloud Platform. That quota is reset for users each day, so instead of bulk download, you could download each file individually until you reach the quota for the day, and download another 0.5 terabyte of files the next day. Alternatively, there is a long-term solution on [requester pays](https://cloud.google.com/storage/docs/requester-pays). Would you be interested in that feature if we enabled it in SCP, where you'd need to provide a billing project before downloading any data?

**Comment by zhanxw** [comment]
Thanks for offering solutions. Unfortunately, our institute does not allow expense on cloud computing. 

A relevant question is how to resume downloading?
This error happened when I was downloading ~500 files.
After a couple of days, I notice the download "finished" but ~100 files have the contents like this:
"The provided token has expired".
Is there a way to re-download them?

**Comment by jlchang** [comment]
Hi @zhanxw,

Please provide some additional context on how this issue came about: 
Is this issue the result of bulk download from a single study? or are you downloading files across multiple studies?

Did the curl command download some files successfully before generating files of content "The provided token has expired"? Or were all files from the curl command problematic?

We're looking into whether we have any technical solutions to offer for resuming the download.

**Comment by jlchang** [comment]
@zhanxw We're working with the study authors for SCP354/slide-seq-study on this issue. We'll let you know when the study has been updated to address the quota issue. If you are experiencing download issues for studies other than SCP354/slide-seq-study, please let us know as the current work will only facilitate downloads for SCP354/slide-seq-study.

**Comment by jlchang** [comment]
@zhanxw The Slide-seq study authors have revised their study summary to include an option to contact them about your interest in bulk download. Please visit their [study summary page](https://portals.broadinstitute.org/single_cell/study/SCP354) and reach out to the Slide-seq team for further assistance with bulk download of that study's data.

**Comment by bistline** [comment]
Closing as study was migrated to new billing project to facilitate downloads.
