### ISSUE TITLE
Information shared when login in with google

### ISSUE THREAD

**Issue by kvittingseerup** [broadinstitute/single_cell_portal#71]
I just tried signing in to the single cell portal and google informed me that in order to do that I needed to allow you guys to:

- View my Google Cloud Platform billing accounts
- View my data in Google Cloud Storage

(see picture below)

I am assuming this is a mistake and what you actually want is to access the basic account information? Would not hurt to update ASAP.

![image](https://user-images.githubusercontent.com/23721187/60263399-d7ac4b80-98e0-11e9-81d9-a7dec2b05d15.png)

**Comment by bistline** [comment]
kvittingseerup -

Thank you for writing.  This is not a mistake, and the scopes requested are intentional.  The Single Cell Portal requires them for the following:

**View Google Cloud Platform Billing Accounts**:  We are asking for only read access to see what billing accounts you have associated with your login.  This is necessary so that the portal can provision projects on your behalf, should you wish to do so.  There is a default project that all users of the portal can utilize at no cost, but we do not allow users to run computes in this project.  Creating your own project will allow you to run analysis workflows directly from the portal.

**View Data in Google Cloud Storage**: We are asking for read access to objects in Google Cloud Storage associated with this account.  This is necessary to allow you to stream objects back to your browser for visualization (such as BAM files in IGV.js).  

I can assure you that no information is shared with any third parties, and we are only asking for **read** access, not **write**.  Please let me know if you have any other questions.

Best,

Jon
Single Cell Portal Team
