### ISSUE TITLE
Please consider compressing text files

### ISSUE THREAD

**Issue by slowkow** [broadinstitute/single_cell_portal#85]
Please consider compressing all of the `.mtx` files.

Here is one example of the savings you can expect to see:

https://singlecell.broadinstitute.org/single_cell/study/SCP259

```
2.3G gene_sorted-Imm.matrix.mtx
477M gene_sorted-Imm.matrix.mtx.gz
```

(477 megabytes) / (2.3 gigabytes) = 0.207

We can expect to save 80%.

- Compressed files are cheaper to store on expensive disks.
- They are faster to download.
- They are also faster to read into memory (with Python, R, etc.).

**Comment by knapii-developments** [comment]
Hey @slowkow -

Are you trying to upload expression data into the portal or trying to download data? Currently, we do allow users to upload compressed data (*.gzip). For downloading, the study creator has control over what files can be downloaded. If the study creator did not upload a compressed file when creating their study, a compressed file will not be available for download.

We appreciate your feedback and we'll consider adding a compressed file option for downloads.

**Comment by slowkow** [comment]
I am downloading.

I would like to ask if you might consider compressing the files after the creator uploads them to the portal. Alternatively, you might also consider asking the creator to compress them before uploading.

**Comment by vickylihorst** [comment]
Hi @slowkow, this is Vicky, product manager for Single Cell Portal.

I definitely share your concerns here as a user who download files from public studies. I think it's also important for study owners to have full control over their study, including deciding what files go into their study and bucket. I can imagine as a study owner, it'd be puzzling to see the files in the study get automatically compressed, and more importantly, it'd be inconvenient to have to go through extra steps to uncompress the file in order to use the file in an analysis pipeline.

We added a ticket to the product backlog to ask study creators to consider compressing the files before uploading. Thank you for using SCP and sharing your feedback!

Please don't hesitate to reach out if you have any further questions.
