### ISSUE TITLE
Gene name association error when with the same spelling but different case

### ISSUE THREAD

**Issue by yulongliu68** [broadinstitute/single_cell_portal#90]
In the newest zebrafish genome, there are genes with the same spelling but one is lower case and the other is upper case. For example, there are dtx4 and DTX4 genes.  In the single-cell portal, those genes show the same expression pattern whereas in R, the actual data, they have different expression patterns.

**Comment by jlchang** [comment]
@yulongliu68,

Thank you for pointing out the case sensitive nature of dtx4 and DTX4 in zebrafish data.

We have always assumed that gene symbols are unique (therefore case insensitive) for genomes - this is the typical genomic convention, including the convention for [zebrafish](https://wiki.zfin.org/display/general/ZFIN+Zebrafish+Nomenclature+Conventions#ZFINZebrafishNomenclatureConventions-1).  Storing gene names in a case insensitive manner allows the portal to offer gene search in a more coherent manner even if genes names are submitted to the portal with different formats (eg. all caps vs lowercase etc) in studies provided by different authors.

Unfortunately in the case of dtx4 and DTX4 there is no way for the portal to store the unique values for both because we have assumed the uniqueness of gene symbols and used a case insensitive storage mechanism for expression data. In searching the latest Zebrafish genome in Ensembl (GRCz11), there is no official DTX4 gene symbol, but there are Zebrafish gene symbols for dtx4a and dtx4b (dtx4 is indicated as a synonym for dtx4b).

As you indicate, the unique expression values for dtx4 and DTX4 are accessible in the files provided by the study author. We regret that those values are currently unavailable for visualization in the portal.

Best regards,

Jean

**Comment by jlchang** [comment]
@yulongliu68,

I've learned that we store expression data in a case-sensitive manner (I will edit my previous reply to remove the erroneous information I provided earlier). The issue is partly because we perform gene search in a case-**in**sensitive manner. The values from both dtx4 and DTX4 are returned for both queries and you are seeing a merged result.

We are looking more deeply into this issue to see if the visualization issue can be addressed. We will let you know what our investigation uncovers.

Regards,

Jean

**Comment by jlchang** [comment]
@yulongliu68 

We have tagged the issue you identified as a bug. We hope to deploy a bugfix to address the issue in our next release on March 5. 

Regards,

Jean

**Comment by jlchang** [comment]
Hi @yulongliu68,

We released a bugfix today and I've confirmed that in the study "A single cell transcriptome atlas of the developing zebrafish hindbrain" (SCP667) gene search from DTX4 and dtx4 now show different expression patterns in the violin plots. If you search for both spellings, you will see different patterns in the dot plot as well.

I hope this resolves the visualization problem you identified in a satisfactory manner. If there are remaining issues, please let me know what you are seeing and which study I should visit to try and reproduce the issue.

Regards,

Jean

**Comment by yulongliu68** [comment]
Thanks! It's correct on my data set now as well.
